export const puppyList = [
  {
    id: 1,
    name: "Sir Waggington",
    email: "sir-wag@email.com",
    image: "src/pupper-img/KTiVXfb.jpg",
    isCute: true,
    age: 5,
    ownerId: 1,
    tricks: [
      { id: 2, title: "Lay Down" },
      { id: 3, title: "Jump through flaming hoop" },
    ],
  },
  {
    id: 2,
    name: "Fiona Penny Pickles",
    email: "pick-your-pennies@email.com",
    image: "src/pupper-img/d9l53WW.jpg",
    isCute: true,
    age: 6,
    ownerId: 1,
    tricks: [],
  },
  {
    id: 3,
    name: "Professor Wagglesworth",
    email: "waggie@email.com",
    image: "src/pupper-img/4qyuADg.jpg",
    isCute: true,
    age: 6,
    ownerId: 2,
    tricks: [{ id: 1, title: "Sit" }],
  },
  {
    id: 4,
    name: "Sergeant Barkowitz",
    email: "the-sarge@email.com",
    image: "src/pupper-img/M7unM1Q.jpg",
    isCute: true,
    age: 4,
    ownerId: 2,
    tricks: [{ id: 2, title: "Lay Down" }],
  },
  {
    id: 5,
    name: "Captain Sniffer",
    email: "capn-sniff@email.com",
    image: "src/pupper-img/FL1w5FO.jpg",
    isCute: true,
    age: 7,
    ownerId: 3,
    tricks: [],
  },
  {
    id: 6,
    name: "Miss Furbulous",
    email: "miss-furby@email.com",
    image: "src/pupper-img/RrQZTaA.jpg",
    isCute: true,
    age: 1,
    ownerId: 3,
    tricks: [],
  },
  {
    id: 7,
    name: "Alfred von Wigglebottom",
    email: "alfie@email.com",
    image: "src/pupper-img/S0tOtqe.jpg",
    isCute: true,
    age: 2,
    ownerId: 3,
    tricks: [],
  },
];